development:
  adapter: postgresql
  encoding: unicode
  database: bmitest
  pool: 5
  username: postgres
  password: aandres1983

test:
  adapter: postgresql
  encoding: unicode
  database: bmitest
  pool: 5
  username: postgres
  password: aandres1983

production:
  adapter: postgresql
  encoding: unicode
  database: bmitest
  pool: 5
  username: postgres
  password: