development:
  adapter: mysql2
  database: bmitest
  host: localhost
  username: root
  password:
  encoding: utf8
  collation: utf8_general_ci

test:
  adapter: mysql2
  database: bmitest
  host: localhost
  username: root
  password:
  encoding: utf8
  collation: utf8_general_ci

production:
  adapter: mysql2
  database: bmitest
  host: localhost
  username: root
  password:
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true